### ISSUE TITLE
Consider moving this under the Tribler organization

### ISSUE THREAD

**Issue by vandenheuvel** [alexander-stannat/Incremental-Pagerank#2]
If @synctext thinks that incremental pagerank is worth more, in-depth research, I think that a repository such as this one should be moved under the Tribler organization.

Pros:

- Everyone will be able to find it
- Requires a significantly higher standard in terms of coding and reporting

Cons:

- Requires a significantly higher standard in terms of coding and reporting

**Comment by alexander-stannat** [comment]
There exists a repository within the tribler organization with the same name. See [here](https://github.com/Tribler/incremental-pagerank)

**Comment by vandenheuvel** [comment]
Alright, then I'll close.
